# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/622b33b1-a7b1-4e9c-966a-32bd5e3b26c0";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2655-7E73";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/622b33b1-a7b1-4e9c-966a-32bd5e3b26c0";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/622b33b1-a7b1-4e9c-966a-32bd5e3b26c0";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/622b33b1-a7b1-4e9c-966a-32bd5e3b26c0";
      fsType = "btrfs";
      options = [ "subvol=@srv" ];
    };

  fileSystems."/srv/.snapshots" =
    { device = "/dev/disk/by-uuid/622b33b1-a7b1-4e9c-966a-32bd5e3b26c0";
      fsType = "btrfs";
      options = [ "subvol=@srv-snapshots" ];
    };

  fileSystems."/srv/scratch" =
    { device = "/dev/disk/by-uuid/622b33b1-a7b1-4e9c-966a-32bd5e3b26c0";
      fsType = "btrfs";
      options = [ "subvol=@scratch" ];
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/d7fd524d-b1d6-48e3-8536-c0d68cf51e6f";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
